apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy-deploy
  name: proxy-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: proxy-deploy
  template:
    metadata:
      labels:
        app: proxy-deploy
    spec:
      containers:
      - image: manedurphy/proxy-service
        name: proxy-service
        env:
        - name: HEADER_DOMAIN
          value: http://photo-header-service:5001
        - name: HOSTEDBY_DOMAIN
          value: http://hosted-by-service:5002
        - name: REDIS_URL
          value: redis://redis-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-deploy
  name: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deploy
  template:
    metadata:
      labels:
        app: redis-deploy
    spec:
      containers:
      - image: redis:6.2.3-alpine
        name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: photo-header-deploy
  name: photo-header-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: photo-header-deploy
  template:
    metadata:
      labels:
        app: photo-header-deploy
    spec:
      containers:
      - image: manedurphy/photo-header-service
        name: photo-header-service
        env:
        - name: HOST
          value: photo-header-db.c8gbra4rkp9f.us-east-1.rds.amazonaws.com
        - name: MYSQL_USER
          value: manedurphy
        - name: MYSQL_PASSWORD
          value: password
        - name: HOSTEDBY_DOMAIN
          value: http://hosted-by-service:5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hosted-by-deploy
  name: hosted-by-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hosted-by-deploy
  template:
    metadata:
      labels:
        app: hosted-by-deploy
    spec:
      containers:
      - image: manedurphy/hosted-by-service
        name: hosted-by-service
        env:
        - name: HOST
          value: hosted-by-db.c8gbra4rkp9f.us-east-1.rds.amazonaws.com
        - name: MYSQL_USER
          value: manedurphy
        - name: MYSQL_PASSWORD
          value: password
