apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: airbnb-clone-cluster
  region: us-east-1
  version: "1.20"

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.small
    minSize: 5
    maxSize: 10
    labels:
      role: workers
      size: small
  - name: managed-ng-2
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    labels:
      role: workers
      size: medium