name: CD Workflow

on:
  push: 
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node Environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Go Environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3

    - name: Install Make & Yarn
      run: |
        sudo apt update -y
        sudo apt-get -y install make
        npm i -g yarn
    
    - name: Install dependencies
      run: |
        yarn
        cd Dane-Proxy && yarn
        cd ../Dane-Service-Header && yarn
        cd ../Dane-Service-HostedBy && yarn

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push images
      run: make docker-push
