name: CD Workflow

on:
  push: 
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node Environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Install Make & Yarn
      run: |
        sudo apt update -y
        sudo apt-get -y install make
        npm i -g yarn
    
    - name: Install dependencies
      run: |
        yarn
        cd static-server && yarn
        cd ../photo-header && yarn
        cd ../hosted-by && yarn

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push images
      run: |
        docker buildx create --name my-builder --use
        make docker-push
