name: CD Workflow

on:
  push: 
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Make
      run: |
        sudo apt update -y
        sudo apt-get -y install make

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Build and push images
      run: make docker-push
